-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ALU_sys_HDL_data_exe_wb is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    a : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    b : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_WREADY : IN STD_LOGIC;
    m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RVALID : IN STD_LOGIC;
    m_axi_gmem2_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_RLAST : IN STD_LOGIC;
    m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BVALID : IN STD_LOGIC;
    m_axi_gmem2_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    c : IN STD_LOGIC_VECTOR (63 downto 0);
    ALU_operation_MEM_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ALU_operation_MEM_ce0 : OUT STD_LOGIC;
    ALU_operation_MEM_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_a_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    data_a_empty_n : IN STD_LOGIC;
    data_a_read : OUT STD_LOGIC;
    data_a_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_a_full_n : IN STD_LOGIC;
    data_a_write : OUT STD_LOGIC;
    data_b_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    data_b_empty_n : IN STD_LOGIC;
    data_b_read : OUT STD_LOGIC;
    data_b_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_b_full_n : IN STD_LOGIC;
    data_b_write : OUT STD_LOGIC;
    data_result_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    data_result_empty_n : IN STD_LOGIC;
    data_result_read : OUT STD_LOGIC;
    data_result_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_result_full_n : IN STD_LOGIC;
    data_result_write : OUT STD_LOGIC );
end;


architecture behav of ALU_sys_HDL_data_exe_wb is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_done : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_idle : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_ready : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WLAST : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_RREADY : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_BREADY : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_data_a_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_data_a_write : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_done : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_idle : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_ready : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WLAST : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_RREADY : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_BREADY : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_data_b_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_data_b_write : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_ap_start : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_ap_done : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_ap_idle : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_ap_ready : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_data_a_read : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_data_b_read : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_data_result_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_exe_fu_92_data_result_write : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_exe_fu_92_ALU_operation_MEM_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_data_exe_wb_Pipeline_exe_fu_92_ALU_operation_MEM_ce0 : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_ap_idle : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_ap_ready : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_data_result_read : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WLAST : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARVALID : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_RREADY : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_BREADY : STD_LOGIC;
    signal grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_data_exe_wb_Pipeline_exe_fu_92_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ALU_sys_HDL_data_exe_wb_Pipeline_l_data_a IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        data_a_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_a_full_n : IN STD_LOGIC;
        data_a_write : OUT STD_LOGIC;
        a : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ALU_sys_HDL_data_exe_wb_Pipeline_l_data_b IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        data_b_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_b_full_n : IN STD_LOGIC;
        data_b_write : OUT STD_LOGIC;
        b : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component ALU_sys_HDL_data_exe_wb_Pipeline_exe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_a_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        data_a_empty_n : IN STD_LOGIC;
        data_a_read : OUT STD_LOGIC;
        data_b_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        data_b_empty_n : IN STD_LOGIC;
        data_b_read : OUT STD_LOGIC;
        data_result_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        data_result_full_n : IN STD_LOGIC;
        data_result_write : OUT STD_LOGIC;
        ALU_operation_MEM_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        ALU_operation_MEM_ce0 : OUT STD_LOGIC;
        ALU_operation_MEM_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ALU_sys_HDL_data_exe_wb_Pipeline_write_back IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_result_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        data_result_empty_n : IN STD_LOGIC;
        data_result_read : OUT STD_LOGIC;
        m_axi_gmem2_AWVALID : OUT STD_LOGIC;
        m_axi_gmem2_AWREADY : IN STD_LOGIC;
        m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_WVALID : OUT STD_LOGIC;
        m_axi_gmem2_WREADY : IN STD_LOGIC;
        m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_WLAST : OUT STD_LOGIC;
        m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_ARVALID : OUT STD_LOGIC;
        m_axi_gmem2_ARREADY : IN STD_LOGIC;
        m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_RVALID : IN STD_LOGIC;
        m_axi_gmem2_RREADY : OUT STD_LOGIC;
        m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_RLAST : IN STD_LOGIC;
        m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_BVALID : IN STD_LOGIC;
        m_axi_gmem2_BREADY : OUT STD_LOGIC;
        m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        c : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_data_exe_wb_Pipeline_l_data_a_fu_74 : component ALU_sys_HDL_data_exe_wb_Pipeline_l_data_a
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start,
        ap_done => grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_done,
        ap_idle => grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_idle,
        ap_ready => grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_ready,
        m_axi_gmem0_AWVALID => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        data_a_din => grp_data_exe_wb_Pipeline_l_data_a_fu_74_data_a_din,
        data_a_full_n => data_a_full_n,
        data_a_write => grp_data_exe_wb_Pipeline_l_data_a_fu_74_data_a_write,
        a => a);

    grp_data_exe_wb_Pipeline_l_data_b_fu_83 : component ALU_sys_HDL_data_exe_wb_Pipeline_l_data_b
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start,
        ap_done => grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_done,
        ap_idle => grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_idle,
        ap_ready => grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_ready,
        m_axi_gmem1_AWVALID => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => ap_const_logic_0,
        m_axi_gmem1_AWADDR => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => ap_const_logic_0,
        m_axi_gmem1_WDATA => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST => m_axi_gmem1_RLAST,
        m_axi_gmem1_RID => m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM => m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER => m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP => m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID => ap_const_logic_0,
        m_axi_gmem1_BREADY => grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => ap_const_lv2_0,
        m_axi_gmem1_BID => ap_const_lv1_0,
        m_axi_gmem1_BUSER => ap_const_lv1_0,
        data_b_din => grp_data_exe_wb_Pipeline_l_data_b_fu_83_data_b_din,
        data_b_full_n => data_b_full_n,
        data_b_write => grp_data_exe_wb_Pipeline_l_data_b_fu_83_data_b_write,
        b => b);

    grp_data_exe_wb_Pipeline_exe_fu_92 : component ALU_sys_HDL_data_exe_wb_Pipeline_exe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_data_exe_wb_Pipeline_exe_fu_92_ap_start,
        ap_done => grp_data_exe_wb_Pipeline_exe_fu_92_ap_done,
        ap_idle => grp_data_exe_wb_Pipeline_exe_fu_92_ap_idle,
        ap_ready => grp_data_exe_wb_Pipeline_exe_fu_92_ap_ready,
        data_a_dout => data_a_dout,
        data_a_empty_n => data_a_empty_n,
        data_a_read => grp_data_exe_wb_Pipeline_exe_fu_92_data_a_read,
        data_b_dout => data_b_dout,
        data_b_empty_n => data_b_empty_n,
        data_b_read => grp_data_exe_wb_Pipeline_exe_fu_92_data_b_read,
        data_result_din => grp_data_exe_wb_Pipeline_exe_fu_92_data_result_din,
        data_result_full_n => data_result_full_n,
        data_result_write => grp_data_exe_wb_Pipeline_exe_fu_92_data_result_write,
        ALU_operation_MEM_address0 => grp_data_exe_wb_Pipeline_exe_fu_92_ALU_operation_MEM_address0,
        ALU_operation_MEM_ce0 => grp_data_exe_wb_Pipeline_exe_fu_92_ALU_operation_MEM_ce0,
        ALU_operation_MEM_q0 => ALU_operation_MEM_q0);

    grp_data_exe_wb_Pipeline_write_back_fu_104 : component ALU_sys_HDL_data_exe_wb_Pipeline_write_back
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start,
        ap_done => grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done,
        ap_idle => grp_data_exe_wb_Pipeline_write_back_fu_104_ap_idle,
        ap_ready => grp_data_exe_wb_Pipeline_write_back_fu_104_ap_ready,
        data_result_dout => data_result_dout,
        data_result_empty_n => data_result_empty_n,
        data_result_read => grp_data_exe_wb_Pipeline_write_back_fu_104_data_result_read,
        m_axi_gmem2_AWVALID => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY => m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY => m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WLAST,
        m_axi_gmem2_WID => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WID,
        m_axi_gmem2_WUSER => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY => ap_const_logic_0,
        m_axi_gmem2_ARADDR => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID => ap_const_logic_0,
        m_axi_gmem2_RREADY => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA => ap_const_lv32_0,
        m_axi_gmem2_RLAST => ap_const_logic_0,
        m_axi_gmem2_RID => ap_const_lv1_0,
        m_axi_gmem2_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem2_RUSER => ap_const_lv1_0,
        m_axi_gmem2_RRESP => ap_const_lv2_0,
        m_axi_gmem2_BVALID => m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY => grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP => m_axi_gmem2_BRESP,
        m_axi_gmem2_BID => m_axi_gmem2_BID,
        m_axi_gmem2_BUSER => m_axi_gmem2_BUSER,
        c => c);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_data_exe_wb_Pipeline_exe_fu_92_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_data_exe_wb_Pipeline_exe_fu_92_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_data_exe_wb_Pipeline_exe_fu_92_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_data_exe_wb_Pipeline_exe_fu_92_ap_ready = ap_const_logic_1)) then 
                    grp_data_exe_wb_Pipeline_exe_fu_92_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_ready = ap_const_logic_1)) then 
                    grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_data_exe_wb_Pipeline_write_back_fu_104_ap_ready = ap_const_logic_1)) then 
                    grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_done, grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_done, grp_data_exe_wb_Pipeline_exe_fu_92_ap_done, grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state12)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_data_exe_wb_Pipeline_exe_fu_92_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ALU_operation_MEM_address0 <= grp_data_exe_wb_Pipeline_exe_fu_92_ALU_operation_MEM_address0;
    ALU_operation_MEM_ce0 <= grp_data_exe_wb_Pipeline_exe_fu_92_ALU_operation_MEM_ce0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done)
    begin
        if ((grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_done)
    begin
        if ((grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_done)
    begin
        if ((grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_data_exe_wb_Pipeline_exe_fu_92_ap_done)
    begin
        if ((grp_data_exe_wb_Pipeline_exe_fu_92_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done, ap_CS_fsm_state12)
    begin
        if ((((grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done, ap_CS_fsm_state12)
    begin
        if (((grp_data_exe_wb_Pipeline_write_back_fu_104_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    data_a_din <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_data_a_din;

    data_a_read_assign_proc : process(grp_data_exe_wb_Pipeline_exe_fu_92_data_a_read, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            data_a_read <= grp_data_exe_wb_Pipeline_exe_fu_92_data_a_read;
        else 
            data_a_read <= ap_const_logic_0;
        end if; 
    end process;


    data_a_write_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_a_fu_74_data_a_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            data_a_write <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_data_a_write;
        else 
            data_a_write <= ap_const_logic_0;
        end if; 
    end process;

    data_b_din <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_data_b_din;

    data_b_read_assign_proc : process(grp_data_exe_wb_Pipeline_exe_fu_92_data_b_read, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            data_b_read <= grp_data_exe_wb_Pipeline_exe_fu_92_data_b_read;
        else 
            data_b_read <= ap_const_logic_0;
        end if; 
    end process;


    data_b_write_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_b_fu_83_data_b_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            data_b_write <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_data_b_write;
        else 
            data_b_write <= ap_const_logic_0;
        end if; 
    end process;

    data_result_din <= grp_data_exe_wb_Pipeline_exe_fu_92_data_result_din;

    data_result_read_assign_proc : process(grp_data_exe_wb_Pipeline_write_back_fu_104_data_result_read, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            data_result_read <= grp_data_exe_wb_Pipeline_write_back_fu_104_data_result_read;
        else 
            data_result_read <= ap_const_logic_0;
        end if; 
    end process;


    data_result_write_assign_proc : process(grp_data_exe_wb_Pipeline_exe_fu_92_data_result_write, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            data_result_write <= grp_data_exe_wb_Pipeline_exe_fu_92_data_result_write;
        else 
            data_result_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_data_exe_wb_Pipeline_exe_fu_92_ap_start <= grp_data_exe_wb_Pipeline_exe_fu_92_ap_start_reg;
    grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_ap_start_reg;
    grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_ap_start_reg;
    grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start <= grp_data_exe_wb_Pipeline_write_back_fu_104_ap_start_reg;
    m_axi_gmem0_ARADDR <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARADDR;
    m_axi_gmem0_ARBURST <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARBURST;
    m_axi_gmem0_ARCACHE <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARCACHE;
    m_axi_gmem0_ARID <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARID;
    m_axi_gmem0_ARLEN <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARLEN;
    m_axi_gmem0_ARLOCK <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARLOCK;
    m_axi_gmem0_ARPROT <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARPROT;
    m_axi_gmem0_ARQOS <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARQOS;
    m_axi_gmem0_ARREGION <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARREGION;
    m_axi_gmem0_ARSIZE <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARSIZE;
    m_axi_gmem0_ARUSER <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARUSER;

    m_axi_gmem0_ARVALID_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARVALID, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_ARVALID <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_ARVALID;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_RREADY, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_gmem0_RREADY <= grp_data_exe_wb_Pipeline_l_data_a_fu_74_m_axi_gmem0_RREADY;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv32_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv4_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    m_axi_gmem1_ARADDR <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARADDR;
    m_axi_gmem1_ARBURST <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARBURST;
    m_axi_gmem1_ARCACHE <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARCACHE;
    m_axi_gmem1_ARID <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARID;
    m_axi_gmem1_ARLEN <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARLEN;
    m_axi_gmem1_ARLOCK <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARLOCK;
    m_axi_gmem1_ARPROT <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARPROT;
    m_axi_gmem1_ARQOS <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARQOS;
    m_axi_gmem1_ARREGION <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARREGION;
    m_axi_gmem1_ARSIZE <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARSIZE;
    m_axi_gmem1_ARUSER <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARUSER;

    m_axi_gmem1_ARVALID_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARVALID, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_gmem1_ARVALID <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_ARVALID;
        else 
            m_axi_gmem1_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;

    m_axi_gmem1_RREADY_assign_proc : process(grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_RREADY, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_gmem1_RREADY <= grp_data_exe_wb_Pipeline_l_data_b_fu_83_m_axi_gmem1_RREADY;
        else 
            m_axi_gmem1_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem1_WDATA <= ap_const_lv32_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv4_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    m_axi_gmem2_ARADDR <= ap_const_lv64_0;
    m_axi_gmem2_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_ARID <= ap_const_lv1_0;
    m_axi_gmem2_ARLEN <= ap_const_lv32_0;
    m_axi_gmem2_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_ARUSER <= ap_const_lv1_0;
    m_axi_gmem2_ARVALID <= ap_const_logic_0;
    m_axi_gmem2_AWADDR <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWADDR;
    m_axi_gmem2_AWBURST <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWBURST;
    m_axi_gmem2_AWCACHE <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWCACHE;
    m_axi_gmem2_AWID <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWID;
    m_axi_gmem2_AWLEN <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWLEN;
    m_axi_gmem2_AWLOCK <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWLOCK;
    m_axi_gmem2_AWPROT <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWPROT;
    m_axi_gmem2_AWQOS <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWQOS;
    m_axi_gmem2_AWREGION <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWREGION;
    m_axi_gmem2_AWSIZE <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWSIZE;
    m_axi_gmem2_AWUSER <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWUSER;

    m_axi_gmem2_AWVALID_assign_proc : process(grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWVALID, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem2_AWVALID <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_AWVALID;
        else 
            m_axi_gmem2_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem2_BREADY_assign_proc : process(grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_BREADY, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem2_BREADY <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_BREADY;
        else 
            m_axi_gmem2_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem2_RREADY <= ap_const_logic_0;
    m_axi_gmem2_WDATA <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WDATA;
    m_axi_gmem2_WID <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WID;
    m_axi_gmem2_WLAST <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WLAST;
    m_axi_gmem2_WSTRB <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WSTRB;
    m_axi_gmem2_WUSER <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WUSER;

    m_axi_gmem2_WVALID_assign_proc : process(grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WVALID, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            m_axi_gmem2_WVALID <= grp_data_exe_wb_Pipeline_write_back_fu_104_m_axi_gmem2_WVALID;
        else 
            m_axi_gmem2_WVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
